# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment:
      name: Polyspace_Environment
      resourceType: VirtualMachine

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: 'Checkout'

          - script: ls -l
            displayName: 'exec ls -l'

          - script: |
              echo "Agent.BuildDirectory:" $(Agent.BuildDirectory)
              echo "Build.Repository.LocalPath:" $(Build.Repository.LocalPath)
              echo "Build.Repository.Name:" $(Build.Repository.Name)
              echo "Build.SourcesDirectory:" $(Build.SourcesDirectory)
            displayName: 'check env variables'

- stage: Analysis
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment:
      name: Polyspace_Environment
      resourceType: VirtualMachine

    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                echo "(test) ls -l: " ls -l
              displayName: 'Run Polyspace Bug Finder Analysis'
