# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment:
    name: Polyspace_Environment
    resourceType: VirtualMachine

  strategy:
   runOnce:
     deploy:
       steps:
       - script: echo Hello, world!
         displayName: 'Run a one-line script'

       - script: ls -l
         displayName: 'exec ls -l'

       - script: echo $(Agent.BuildDirectory)
         workingDirectory: $(Agent.BuildDirectory)
         displayName: 'exec Agent.BuildDirectory'

       - script: echo $(Agent.Build.Repository.LocalPath)
         displayName: 'exec Agent.Build.Repository.LocalPath'

       - script: echo $(Agent.Build.Repository.Name)
         displayName: 'exec Agent.Build.Repository.Name'

       - script: echo $(Agent.Build.SourcesDirectory)
         displayName: 'Agent.Build.SourcesDirectory'

       - script: |
           echo Add other tasks to build, test, and deploy your project.
           echo See https://aka.ms/yaml
         displayName: 'Run a multi-line script'
